services:
  db:
    image: mysql
    container_name: db_server
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: int221_tt2
      TZ: Asia/Bangkok
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - tt2_network

  backend:
    container_name: backend_server
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      db:
        condition: "service_healthy"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/int221_tt2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    restart: unless-stopped
    networks:
      - tt2_network

  frontend:
    container_name: frontend_server
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - tt2_network

networks:
  tt2_network:
    driver: bridge

volumes:
  mysql_data:
